[package]
name = "urgeopts"
version = "0.1.0"
authors = ["Fumiaki Kinoshita <fumiexcel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.0" }
yaml-rust = "0.3.5"