[package]
name = "urgeopts"
description = "rich getopts replacement for shell script"
homepage = "https://github.com/fumieval/urgeopts"
version = "0.1.2"
authors = ["Fumiaki Kinoshita <fumiexcel@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
categories = ["command-line-utilities", "command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.33.0" }
yaml-rust = "0.3.5"